// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3f_l7S_l4nsrFucOhDZ9BhdU0mVKFao',
    appId: '1:429265731140:web:a3e7c8c9d72cbee0f14611',
    messagingSenderId: '429265731140',
    projectId: 'bibliotecaflutter-3c9a9',
    authDomain: 'bibliotecaflutter-3c9a9.firebaseapp.com',
    storageBucket: 'bibliotecaflutter-3c9a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQPbht62tjVXlXZCBGRCeHTvbcq-bVlPI',
    appId: '1:429265731140:android:3823b60fc541c1c4f14611',
    messagingSenderId: '429265731140',
    projectId: 'bibliotecaflutter-3c9a9',
    storageBucket: 'bibliotecaflutter-3c9a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiFNFg4IvMo97lS9PoZZa09OGjH4Ra-As',
    appId: '1:429265731140:ios:32b195d2094170d6f14611',
    messagingSenderId: '429265731140',
    projectId: 'bibliotecaflutter-3c9a9',
    storageBucket: 'bibliotecaflutter-3c9a9.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiFNFg4IvMo97lS9PoZZa09OGjH4Ra-As',
    appId: '1:429265731140:ios:32b195d2094170d6f14611',
    messagingSenderId: '429265731140',
    projectId: 'bibliotecaflutter-3c9a9',
    storageBucket: 'bibliotecaflutter-3c9a9.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-3f_l7S_l4nsrFucOhDZ9BhdU0mVKFao',
    appId: '1:429265731140:web:26854d1acabd0e49f14611',
    messagingSenderId: '429265731140',
    projectId: 'bibliotecaflutter-3c9a9',
    authDomain: 'bibliotecaflutter-3c9a9.firebaseapp.com',
    storageBucket: 'bibliotecaflutter-3c9a9.firebasestorage.app',
  );
}
