name: biblioteca_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  pdf: ^3.11.3
  printing: ^5.14.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/Images/logoBiblioteca.jpg
